#use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
target 'MercurySDK_Example' do
  pod 'Masonry'
  pod 'SDWebImage'
  pod 'MercurySDK', :path => '../'
#  pod 'AdvanceSDK', '~> 3.2.6.0' # 可指定你想要的版本号

end
